import type { TouristPlace } from "./types"

export const touristPlaces: TouristPlace[] = [
  {
    id: "1",
    name: "Matterhorn",
    country: "Switzerland",
    description:
      "The iconic pyramid-shaped mountain in the Swiss Alps. Experience breathtaking views, world-class skiing, and charming alpine villages.",
    price: 125000,
    rating: 4.9,
    address: "Zermatt, Valais, Switzerland",
    image: "/matterhorn-mountain-switzerland-scenic-view.jpg",
    location: { lat: 45.9763, lng: 7.6586 },
    accommodation: {
      name: "Alpine Grand Hotel",
      type: "4-Star Mountain Resort",
      rating: 4.8,
      pricePerNight: 12000,
      included: true,
    },
    transportation: {
      carRental: 8000,
      localTransport: 3500,
      airportTransfer: 4500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 3500,
    },
    offers: {
      cashback: 6250,
      cashbackPercentage: 5,
      specialOffer: "Book now and get free skiing pass worth ₹5000",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "101",
    name: "Taj Mahal",
    country: "Agra, India",
    description:
      "The symbol of eternal love and a UNESCO World Heritage Site. Marvel at this ivory-white marble mausoleum, one of the Seven Wonders of the World.",
    price: 22000,
    rating: 5.0,
    address: "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001",
    image: "/taj-mahal-agra-sunrise-white-marble-monument.jpg",
    location: { lat: 27.1751, lng: 78.0421 },
    accommodation: {
      name: "Oberoi Amarvilas",
      type: "5-Star Luxury Hotel",
      rating: 4.9,
      pricePerNight: 8500,
      included: true,
    },
    transportation: {
      carRental: 2500,
      localTransport: 1500,
      airportTransfer: 2000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 1650,
      cashbackPercentage: 7.5,
      specialOffer: "All meals included + Free Taj Mahal guide + Visit to Agra Fort",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "102",
    name: "Goa Beaches",
    country: "Goa, India",
    description:
      "India's beach paradise with golden sand beaches, Portuguese heritage, vibrant nightlife, water sports, and delicious seafood.",
    price: 18000,
    rating: 4.7,
    address: "North Goa & South Goa, Goa 403001",
    image: "/goa-beach-palm-trees-sunset-coastal-india.jpg",
    location: { lat: 15.2993, lng: 74.124 },
    accommodation: {
      name: "Taj Exotica Resort & Spa",
      type: "5-Star Beach Resort",
      rating: 4.8,
      pricePerNight: 6500,
      included: true,
    },
    transportation: {
      carRental: 2000,
      localTransport: 1200,
      airportTransfer: 1500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 1500,
    },
    offers: {
      cashback: 1440,
      cashbackPercentage: 8,
      specialOffer: "Water sports package + Beach shack dinner + Dolphin watching tour",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "103",
    name: "Kerala Backwaters",
    country: "Kerala, India",
    description:
      "God's Own Country with serene backwaters, lush green landscapes, traditional houseboats, Ayurvedic treatments, and pristine hill stations.",
    price: 25000,
    rating: 4.8,
    address: "Alleppey (Alappuzha), Kerala 688001",
    image: "/kerala-backwaters-houseboat-palm-trees-serene.jpg",
    location: { lat: 9.4981, lng: 76.3388 },
    accommodation: {
      name: "Premium Houseboat Stay",
      type: "Deluxe Houseboat",
      rating: 4.9,
      pricePerNight: 7500,
      included: true,
    },
    transportation: {
      carRental: 3000,
      localTransport: 1500,
      airportTransfer: 2500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 2000,
      cashbackPercentage: 8,
      specialOffer: "All authentic Kerala meals + Ayurvedic massage + Tea plantation visit",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "104",
    name: "Jaipur - Pink City",
    country: "Rajasthan, India",
    description:
      "The royal heritage city with majestic palaces, historic forts, vibrant bazaars, and rich Rajasthani culture. Experience the royal grandeur.",
    price: 20000,
    rating: 4.7,
    address: "Jaipur, Rajasthan 302001",
    image: "/jaipur-hawa-mahal-amber-fort-pink-city-rajasthan.jpg",
    location: { lat: 26.9124, lng: 75.7873 },
    accommodation: {
      name: "Rambagh Palace Hotel",
      type: "5-Star Heritage Palace",
      rating: 4.9,
      pricePerNight: 7000,
      included: true,
    },
    transportation: {
      carRental: 2500,
      localTransport: 1200,
      airportTransfer: 1800,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 1200,
    },
    offers: {
      cashback: 1600,
      cashbackPercentage: 8,
      specialOffer: "Elephant ride at Amber Fort + City Palace entry + Cultural evening show",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "105",
    name: "Manali",
    country: "Himachal Pradesh, India",
    description:
      "Himalayan hill station with snow-capped mountains, adventure sports, ancient temples, and scenic valleys. Perfect for nature lovers and adventure seekers.",
    price: 16000,
    rating: 4.6,
    address: "Manali, Himachal Pradesh 175131",
    image: "/manali-snow-mountains-himalaya-valley-adventure.jpg",
    location: { lat: 32.2432, lng: 77.1892 },
    accommodation: {
      name: "Himalayan Heights Resort",
      type: "4-Star Mountain Resort",
      rating: 4.7,
      pricePerNight: 5500,
      included: true,
    },
    transportation: {
      carRental: 3500,
      localTransport: 1500,
      airportTransfer: 3000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 1000,
    },
    offers: {
      cashback: 1280,
      cashbackPercentage: 8,
      specialOffer: "Solang Valley visit + Paragliding discount + Bonfire evening",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "106",
    name: "Varanasi",
    country: "Uttar Pradesh, India",
    description:
      "The spiritual capital of India. Experience ancient ghats, Ganga Aarti, historic temples, and the mystical atmosphere of this holy city.",
    price: 14000,
    rating: 4.8,
    address: "Varanasi, Uttar Pradesh 221001",
    image: "/varanasi-ganges-river-ghats-temples-spiritual.jpg",
    location: { lat: 25.3176, lng: 82.9739 },
    accommodation: {
      name: "Ganges View Hotel",
      type: "4-Star Heritage Hotel",
      rating: 4.6,
      pricePerNight: 4500,
      included: true,
    },
    transportation: {
      carRental: 2000,
      localTransport: 1000,
      airportTransfer: 1500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 800,
    },
    offers: {
      cashback: 1120,
      cashbackPercentage: 8,
      specialOffer: "Ganga Aarti boat ride + Sarnath Buddhist temple visit + City tour",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "107",
    name: "Udaipur - City of Lakes",
    country: "Rajasthan, India",
    description:
      "The Venice of the East with stunning lakes, magnificent palaces, romantic boat rides, and rich cultural heritage. Most romantic city in India.",
    price: 19000,
    rating: 4.8,
    address: "Udaipur, Rajasthan 313001",
    image: "/udaipur-lake-palace-city-palace-rajasthan-romantic.jpg",
    location: { lat: 24.5854, lng: 73.7125 },
    accommodation: {
      name: "Lake Pichola Heritage Hotel",
      type: "5-Star Lakeside Hotel",
      rating: 4.8,
      pricePerNight: 6500,
      included: true,
    },
    transportation: {
      carRental: 2200,
      localTransport: 1200,
      airportTransfer: 1800,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 1500,
    },
    offers: {
      cashback: 1520,
      cashbackPercentage: 8,
      specialOffer: "Lake Pichola boat ride + City Palace entry + Cultural dance show",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "108",
    name: "Leh-Ladakh",
    country: "Jammu & Kashmir, India",
    description:
      "The land of high passes with breathtaking landscapes, Buddhist monasteries, pristine lakes, and thrilling mountain roads. Adventure paradise.",
    price: 28000,
    rating: 4.9,
    address: "Leh, Ladakh, Jammu & Kashmir 194101",
    image: "/leh-ladakh-mountains-pangong-lake-monastery-advent.jpg",
    location: { lat: 34.1526, lng: 77.577 },
    accommodation: {
      name: "Ladakh Mountain Resort",
      type: "4-Star Mountain Hotel",
      rating: 4.6,
      pricePerNight: 6000,
      included: true,
    },
    transportation: {
      carRental: 5000,
      localTransport: 2500,
      airportTransfer: 2000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 2240,
      cashbackPercentage: 8,
      specialOffer: "All meals + Pangong Lake trip + Nubra Valley visit + Monastery tour",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "109",
    name: "Andaman Islands",
    country: "Andaman & Nicobar, India",
    description:
      "Tropical paradise with pristine beaches, crystal clear waters, coral reefs, water sports, and exotic marine life. Perfect for beach lovers.",
    price: 32000,
    rating: 4.8,
    address: "Port Blair, Andaman & Nicobar Islands 744101",
    image: "/andaman-islands-beach-clear-water-coral-reef-tropi.jpg",
    location: { lat: 11.7401, lng: 92.6586 },
    accommodation: {
      name: "Havelock Beach Resort",
      type: "4-Star Beach Resort",
      rating: 4.7,
      pricePerNight: 7500,
      included: true,
    },
    transportation: {
      carRental: 0,
      localTransport: 3000,
      airportTransfer: 3500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 2560,
      cashbackPercentage: 8,
      specialOffer: "All meals + Scuba diving session + Island hopping + Water sports",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "110",
    name: "Rishikesh",
    country: "Uttarakhand, India",
    description:
      "Yoga capital of the world with the holy Ganges, adventure sports like rafting and bungee jumping, ashrams, and spiritual experiences.",
    price: 12000,
    rating: 4.6,
    address: "Rishikesh, Uttarakhand 249201",
    image: "/rishikesh-ganges-river-rafting-yoga-lakshman-jhula.jpg",
    location: { lat: 30.0869, lng: 78.2676 },
    accommodation: {
      name: "Riverside Adventure Camp",
      type: "3-Star Camp Resort",
      rating: 4.5,
      pricePerNight: 3500,
      included: true,
    },
    transportation: {
      carRental: 2500,
      localTransport: 1000,
      airportTransfer: 2500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 960,
      cashbackPercentage: 8,
      specialOffer: "All vegetarian meals + River rafting + Yoga session + Ganga Aarti",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "111",
    name: "Darjeeling",
    country: "West Bengal, India",
    description:
      "The Queen of Hills with stunning views of Kanchenjunga, tea gardens, toy train ride, colonial charm, and pleasant climate year-round.",
    price: 15000,
    rating: 4.7,
    address: "Darjeeling, West Bengal 734101",
    image: "/darjeeling-tea-gardens-mountains-toy-train-himalay.jpg",
    location: { lat: 27.036, lng: 88.2627 },
    accommodation: {
      name: "Windamere Hotel",
      type: "4-Star Heritage Hotel",
      rating: 4.6,
      pricePerNight: 5000,
      included: true,
    },
    transportation: {
      carRental: 2500,
      localTransport: 1200,
      airportTransfer: 2800,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 1000,
    },
    offers: {
      cashback: 1200,
      cashbackPercentage: 8,
      specialOffer: "Toy train ride + Tea garden tour + Tiger Hill sunrise + Cable car",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "112",
    name: "Hampi",
    country: "Karnataka, India",
    description:
      "UNESCO World Heritage Site with magnificent ruins of Vijayanagara Empire, ancient temples, boulder-strewn landscapes, and rich history.",
    price: 13000,
    rating: 4.7,
    address: "Hampi, Karnataka 583239",
    image: "/hampi-ancient-ruins-temples-boulders-karnataka-her.jpg",
    location: { lat: 15.335, lng: 76.46 },
    accommodation: {
      name: "Heritage Resort Hampi",
      type: "3-Star Heritage Hotel",
      rating: 4.5,
      pricePerNight: 4000,
      included: true,
    },
    transportation: {
      carRental: 2000,
      localTransport: 1000,
      airportTransfer: 2500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 800,
    },
    offers: {
      cashback: 1040,
      cashbackPercentage: 8,
      specialOffer: "Heritage guided tour + Sunset point visit + Coracle boat ride",
    },
    duration: {
      days: 3,
      nights: 2,
    },
  },
  {
    id: "2",
    name: "Eiffel Tower",
    country: "Paris, France",
    description:
      "The most iconic landmark in Paris. Enjoy panoramic views of the City of Light from the top, romantic Seine River cruises, and world-class cuisine.",
    price: 95000,
    rating: 4.8,
    address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France",
    image: "/eiffel-tower-paris-sunset-romantic.jpg",
    location: { lat: 48.8584, lng: 2.2945 },
    accommodation: {
      name: "Hotel Le Paris",
      type: "3-Star Boutique Hotel",
      rating: 4.6,
      pricePerNight: 9500,
      included: true,
    },
    transportation: {
      carRental: 5000,
      localTransport: 2500,
      airportTransfer: 3000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 4000,
    },
    offers: {
      cashback: 4750,
      cashbackPercentage: 5,
      specialOffer: "Complimentary Seine River Cruise included",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "3",
    name: "Maldives Beach Resort",
    country: "Maldives",
    description:
      "Paradise on Earth with crystal-clear waters, pristine white beaches, and luxury overwater bungalows. Perfect for honeymoons and relaxation.",
    price: 185000,
    rating: 5.0,
    address: "Malé Atoll, Maldives",
    image: "/maldives-overwater-bungalows-crystal-clear-water-b.jpg",
    location: { lat: 3.2028, lng: 73.2207 },
    accommodation: {
      name: "Paradise Overwater Villa",
      type: "5-Star Luxury Resort",
      rating: 5.0,
      pricePerNight: 25000,
      included: true,
    },
    transportation: {
      carRental: 0,
      localTransport: 5000,
      airportTransfer: 8000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 13875,
      cashbackPercentage: 7.5,
      specialOffer: "All meals included + Free spa session worth ₹8000",
    },
    duration: {
      days: 6,
      nights: 5,
    },
  },
  {
    id: "4",
    name: "Santorini",
    country: "Greece",
    description:
      "Famous for stunning sunsets, white-washed buildings with blue domes, and breathtaking caldera views. A romantic Mediterranean escape.",
    price: 110000,
    rating: 4.9,
    address: "Santorini, Cyclades, Greece",
    image: "/santorini-greece-blue-dome-white-buildings-sunset.jpg",
    location: { lat: 36.3932, lng: 25.4615 },
    accommodation: {
      name: "Caldera View Hotel",
      type: "4-Star Cliffside Hotel",
      rating: 4.9,
      pricePerNight: 11000,
      included: true,
    },
    transportation: {
      carRental: 6000,
      localTransport: 2000,
      airportTransfer: 3500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 3000,
    },
    offers: {
      cashback: 6600,
      cashbackPercentage: 6,
      specialOffer: "Wine tasting tour included",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "5",
    name: "Bali",
    country: "Indonesia",
    description:
      "Tropical paradise with lush rice terraces, ancient temples, pristine beaches, and vibrant culture. Perfect for adventure and relaxation.",
    price: 75000,
    rating: 4.7,
    address: "Bali, Indonesia",
    image: "/bali-indonesia-rice-terraces-temple-beach-tropical.jpg",
    location: { lat: -8.3405, lng: 115.092 },
    accommodation: {
      name: "Ubud Rice View Resort",
      type: "3-Star Beach Resort",
      rating: 4.7,
      pricePerNight: 7500,
      included: true,
    },
    transportation: {
      carRental: 3500,
      localTransport: 2000,
      airportTransfer: 2500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 1500,
    },
    offers: {
      cashback: 4500,
      cashbackPercentage: 6,
      specialOffer: "Temple tour + Traditional massage included",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "6",
    name: "Dubai",
    country: "United Arab Emirates",
    description:
      "Luxury destination with the world's tallest building, indoor skiing, desert safaris, and opulent shopping malls. Where tradition meets modernity.",
    price: 140000,
    rating: 4.6,
    address: "Dubai, United Arab Emirates",
    image: "/dubai-burj-khalifa-skyline-night-lights-luxury.jpg",
    location: { lat: 25.2048, lng: 55.2708 },
    accommodation: {
      name: "Burj View Luxury Hotel",
      type: "5-Star City Hotel",
      rating: 4.8,
      pricePerNight: 15000,
      included: true,
    },
    transportation: {
      carRental: 8000,
      localTransport: 3000,
      airportTransfer: 4000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 4500,
    },
    offers: {
      cashback: 8400,
      cashbackPercentage: 6,
      specialOffer: "Free Burj Khalifa ticket + Desert Safari",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "7",
    name: "Machu Picchu",
    country: "Peru",
    description:
      "Ancient Incan citadel set high in the Andes Mountains. A UNESCO World Heritage site with stunning mountain scenery and rich history.",
    price: 165000,
    rating: 4.9,
    address: "Cusco Region, Peru",
    image: "/machu-picchu-peru-ancient-ruins-mountains.jpg",
    location: { lat: -13.1631, lng: -72.545 },
    accommodation: {
      name: "Andes Mountain Lodge",
      type: "4-Star Heritage Hotel",
      rating: 4.7,
      pricePerNight: 13000,
      included: true,
    },
    transportation: {
      carRental: 7000,
      localTransport: 4000,
      airportTransfer: 5000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: true,
      dinner: true,
      estimatedCostPerDay: 0,
    },
    offers: {
      cashback: 11550,
      cashbackPercentage: 7,
      specialOffer: "Guided heritage tour + All meals included",
    },
    duration: {
      days: 6,
      nights: 5,
    },
  },
  {
    id: "8",
    name: "Tokyo",
    country: "Japan",
    description:
      "Vibrant metropolis blending traditional temples with modern technology. Experience cherry blossoms, sushi, anime culture, and neon-lit streets.",
    price: 105000,
    rating: 4.8,
    address: "Tokyo, Japan",
    image: "/tokyo-japan-cherry-blossoms-city-skyline-temple.jpg",
    location: { lat: 35.6762, lng: 139.6503 },
    accommodation: {
      name: "Shibuya City Hotel",
      type: "4-Star Modern Hotel",
      rating: 4.8,
      pricePerNight: 10500,
      included: true,
    },
    transportation: {
      carRental: 5500,
      localTransport: 3000,
      airportTransfer: 3500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 3500,
    },
    offers: {
      cashback: 6300,
      cashbackPercentage: 6,
      specialOffer: "JR Pass included for unlimited train travel",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "9",
    name: "Iceland",
    country: "Iceland",
    description:
      "Land of fire and ice with stunning waterfalls, geysers, hot springs, Northern Lights, and dramatic volcanic landscapes.",
    price: 155000,
    rating: 4.8,
    address: "Reykjavik, Iceland",
    image: "/iceland-northern-lights-aurora-waterfall-volcanic-.jpg",
    location: { lat: 64.9631, lng: -19.0208 },
    accommodation: {
      name: "Northern Lights Inn",
      type: "4-Star Eco Lodge",
      rating: 4.7,
      pricePerNight: 14000,
      included: true,
    },
    transportation: {
      carRental: 9000,
      localTransport: 3500,
      airportTransfer: 4500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: true,
      estimatedCostPerDay: 4000,
    },
    offers: {
      cashback: 10850,
      cashbackPercentage: 7,
      specialOffer: "Northern Lights tour + Blue Lagoon entry included",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
  {
    id: "10",
    name: "New York City",
    country: "United States",
    description:
      "The city that never sleeps. Experience iconic landmarks like Times Square, Statue of Liberty, Central Park, and world-class museums.",
    price: 135000,
    rating: 4.7,
    address: "New York, NY, United States",
    image: "/new-york-city-skyline-times-square-statue-of-liber.jpg",
    location: { lat: 40.7128, lng: -74.006 },
    accommodation: {
      name: "Manhattan Plaza Hotel",
      type: "4-Star City Center Hotel",
      rating: 4.6,
      pricePerNight: 13500,
      included: true,
    },
    transportation: {
      carRental: 7000,
      localTransport: 3500,
      airportTransfer: 4000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 5000,
    },
    offers: {
      cashback: 6750,
      cashbackPercentage: 5,
      specialOffer: "Empire State Building + Statue of Liberty tickets included",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "11",
    name: "Venice",
    country: "Italy",
    description:
      "Romantic city of canals, gondolas, and stunning architecture. Explore St. Mark's Square, Rialto Bridge, and authentic Italian cuisine.",
    price: 98000,
    rating: 4.8,
    address: "Venice, Italy",
    image: "/venice-italy-canals-gondola-bridges-romantic-sunse.jpg",
    location: { lat: 45.4408, lng: 12.3155 },
    accommodation: {
      name: "Canal View Boutique",
      type: "3-Star Historic Hotel",
      rating: 4.7,
      pricePerNight: 9800,
      included: true,
    },
    transportation: {
      carRental: 0,
      localTransport: 3500,
      airportTransfer: 3000,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 3500,
    },
    offers: {
      cashback: 5880,
      cashbackPercentage: 6,
      specialOffer: "Gondola ride + Italian cooking class included",
    },
    duration: {
      days: 4,
      nights: 3,
    },
  },
  {
    id: "12",
    name: "Phuket",
    country: "Thailand",
    description:
      "Thailand's largest island with beautiful beaches, vibrant nightlife, Buddhist temples, and delicious street food. Perfect tropical getaway.",
    price: 68000,
    rating: 4.6,
    address: "Phuket, Thailand",
    image: "/phuket-thailand-beach-tropical-island-temple-boats.jpg",
    location: { lat: 7.8804, lng: 98.3923 },
    accommodation: {
      name: "Patong Beach Resort",
      type: "3-Star Beachfront Hotel",
      rating: 4.6,
      pricePerNight: 6800,
      included: true,
    },
    transportation: {
      carRental: 3000,
      localTransport: 2000,
      airportTransfer: 2500,
    },
    foodArrangement: {
      breakfast: true,
      lunch: false,
      dinner: false,
      estimatedCostPerDay: 1200,
    },
    offers: {
      cashback: 5100,
      cashbackPercentage: 7.5,
      specialOffer: "Island hopping tour + Thai massage included",
    },
    duration: {
      days: 5,
      nights: 4,
    },
  },
]
